#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
	cd /usr/bin/dlr-bluetooth
	# wipe old pids of scripts
	> .pid
	for script in *.sh; do
		logger -t DLR_BT "starting $PWD/$script"
		./$script &
		echo $! >> .pid
	done
}   

stop() {
	rkill() {
		for pid in $(pgrep -P $1); do
			rkill $pid
			kill -9 $pid
		done
	}
	cd /usr/bin/dlr-bluetooth
	[ -r .pid ] || exit 0
	for pid in $(cat .pid); do
		rkill $pid
	done
	rm -f .pid
}